<a href="https://colab.research.google.com/github/KindBer/Examen/blob/master/Quiz2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Importing dependencies**

In [ ]:
# Since Collab is being used, it is necessary to install Pytorch
!pip install torch
import torch as torch

import numpy as np
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm

A = torch.tensor([[4.0, -5.0], [-2.0, 3.0]])
print(A)

tensor([[ 4., -5.],
        [-2.,  3.]])


In [ ]:
#matrix del quiz
A = torch.tensor([[5, 2, 7], [8, 1, 5], [3, 1, 3]])
print("Valor de A: ")
print(A)
print("\n")

def isSymmetric(B):
    """
    B: input matrix
    """
    Bt = B.transpose(0, 1)
    return (torch.all(B.eq(Bt)))

def isAntisymmetric(C):
    """
    C: input matrix
    """
    Ct = C.transpose(0, 1)
    
    return (torch.all(C.eq(-Ct)))

#simetria
At = A.transpose(0, 1)
Sym = 1/2 * (A + At)

#print simetria
print("Symmetric: ")
print(Sym)
print(isSymmetric(Sym))
print("\n")

#anti-simetria
nAt = A.transpose(0, 1)
Asym = 1/2 * (A - nAt)

#print anti-simetria
print("Anti-symmetric: ")
print(Asym)
print(isAntisymmetric(Asym))
print("\n")




#isSymmetric(externalProduct2)   

Valor de A: 
tensor([[5, 2, 7],
        [8, 1, 5],
        [3, 1, 3]])


Symmetric: 
tensor([[5., 5., 5.],
        [5., 1., 3.],
        [5., 3., 3.]])
tensor(True)


Anti-symmetric: 
tensor([[ 0., -3.,  2.],
        [ 3.,  0.,  2.],
        [-2., -2.,  0.]])
tensor(True)


